#!/bin/bash

source /opt/resource/common.sh

files=$(get_latest_files "${user}" "${host}" "${glob}" "${version}" "${basedir}")

json="[]"
IFS=$'\n'
for file in $(echo "$files"); do
	file=$(basename $file)
	json=$(echo $json | jq --arg file $file -r '. |= .+ [{ path: "$file"}]')
done

echo "${json}"
