#!/bin/bash

source /opt/resource/common.sh

outdir=$1

cd $outdir

scp -o StrictHostKeyChecking=no ${user}@${host}:${version} .

echo "{}" | jq --arg path ${version} '. |= .+ {version:{path: $path}, metadata:[]}'
