#!/bin/bash

source /opt/resource/common.sh

outdir=$1
cd $outdir

files=$(get_latest_files "${user}" "${host}" "${glob}" "${version}" "${basedir}")

IFS=$'\n'
for file in $(output "$files"); do
	file=$(basename ${file})
	scp -o StrictHostKeyChecking=no ${user}@${host}:${basedir}/${file} .
done

output "{}" | jq --arg path ${file} '. |= .+ {version:{path: $path}, metadata:[]}'
