#!/bin/bash

source /opt/resource/common.sh
workdir=$1

cd ${workdir}

#overwrite common glob
glob=$(output ${input_json} | jq -r '.params.glob')
dest=$(output ${input_json} | jq -r '.params.destdir')

latest_file=$(ls -lt ${glob} | awk '/^\-/{print $(NF)}' | head -n1)

scp -o StrictHostKeyChecking=no ${glob} ${user}@${host}:${dest}/

latest_file=$(basename ${latest_file})
output "{}" | jq --arg latest ${latest_file} '. |= .+ {version:{path:$latest}, metadata:[]}'
