---
resources:
- name: source
  type: git
  source:
    uri: git@github.com:ECSTeam/scp-resource.git
    private_key: {{github-private-key}}
- name: version
  type: semver
  source:
    driver: git
    uri: git@github.com:ECSTeam/commissions-calculator.git
    branch: version
    file: version
    private_key: {{github-private-key}}
    initial_version: 1.0.0
- name: docker-hub
  type: docker-image
  source:
    repository: ecsteam/scp-resource
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}

jobs:
- name: package
  public: true
  plan:
  - aggregate:
    - get: source
      trigger: true
    - get: version
  - put: docker-hub
    params:
      build: source
      tag: version/version
      tag_prefix: v
      tag_as_latest: true
  - put: version
    params: { bump: patch }
- name: bump-minor
  public: true
  plan:
  - get: version
    params: { bump: minor }
  - put: version
    params: { file: version/number }
- name: bump-major
  public: true
  plan:
  - get: version
    params: { bump: major }
  - put: version
    params: { file: version/number }
